name: Chatbot with Guardrails
description: "AMP showcasing NeMo Guardrails, Langchain, OpenAI Embeddings, Pinecone, and Streamlit to create a complete Chatbot usecase with Guardrails."
author: "Kevin Talbert"
date: "2024-2-2"
specification_version: 1.0
prototype_version: 1.0
environment_variables:
  OPENAI_API_KEY:
    default: ""
    description: "Access key ID for interacting with OpenAI API"
    required: true
  OPENAI_EMBEDDING_MODEL:
    default: "text-embedding-ada-002"
    description: "Embedding model for OpenAI to use (Default is the text-embedding-ada-002 embedding model). Changing this will require manually adjusting the Rails configural file in 2_app/config.yml."
    required: true
  OPENAI_LLM_COMPLETION_MODEL:
    default: "gpt-3.5-turbo"
    description: "Completion model for OpenAI to use (Default is the gpt-3.5-turbo completion model). Changing this will require manually adjusting the Rails configural file in 2_app/config.yml."
    required: true
  PINECONE_API_KEY:
    default: ""
    description: "Access key ID for interacting with Pinecone API"
    required: true
  PINECONE_ENVIRONMENT:
    default: "gcp-starter"
    description: "Required for Pinecone Vector DB: Enter your Pinecone environment here. For the free account, gcp-starter is the default. (Shown in API Keys page)"
    required: true
  PINECONE_INDEX:
    default: "cml-guardrails"
    description: "Required for Pinecone Vector DB: The default is 'cml-guardrails' and can be changed to identify variations for organizations with multiple indexes."
    required: true
    
runtimes: 
  - editor: JupyterLab
    kernel: Python 3.11
    edition: Standard
  
tasks:
  - type: run_session
    name: Install Dependencies
    script: 0_session-install-deps/install-dependencies.py
    short_summary: Install Dependencies
    kernel: python3
    cpu: 2
    memory: 8

  - type: create_job
    name: Load PDFs to Pinecone
    entity_label: load-to-pinecone
    script: 1_job-load-docs-to-pinecone/load-to-pinecone.py
    arguments: None
    short_summary: Create/Load PDF embeddings to Pinecone
    long_summary: Job to create PDF document embeddings and subsequently load the created PDF embeddings to Pinecone.
    cpu: 2
    memory: 4
    environment:
      TASK_TYPE: CREATE/RUN_JOB

  - type: run_job
    entity_label: load-to-pinecone
    short_summary: Populate Pinecone with PDF documents embeddings

  - type: start_application
    name: Guardrails Chatbot
    subdomain: guardrails-chatbot
    script: launch-app.py
    short_summary: Create and start Chatbot with Guardrails Streamlit app.
    long_summary: Create and start Chatbot with Guardrails Streamlit app. Remember to enable unauthenticated app access for external access to the UI.
    cpu: 2
    memory: 8
    environment_variables:
      TASK_TYPE: START_APPLICATION
